services:
  lndg:
    build: .
    volumes:
      - /root/.lnd:/root/.lnd:ro
      - /root/lndg/data:/lndg/data:rw
    command:
      - sh
      - -c
      - python initialize.py -net 'mainnet' -server 'localhost:10009' -d && supervisord && python manage.py runserver 0.0.0.0:8000
    ports:
      - 8889:8000